version: '3.1'

services:
  mhd:
    container_name: mhd
    build: .
    restart: unless-stopped
    ports:
     - "8080:8080"
    command: --debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3